spring.application.name=TpCafe_Attafi_Nouha
spring.datasource.url=jdbc:mysql://localhost:3306/cafedb\
?createDatabaseIfNotExist=true\
&useUnicode=true\
&useJDBCCompliantTimezoneShift=true\
&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
server.port=8088
server.servlet.context-path=/firstProject
### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update