spring.application.name=TpCafe_Attafi_Nouha

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/cafedb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=8088
server.servlet.context-path=/firstProject

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
